version: "3"
services:
    zabbix_server:
        container_name: zabbix_server
        image: zabbix/zabbix-server-mysql:alpine-4.4.3
        restart: always
        ports:
            - "162:162/udp"
            - "10051:10051"            
        environment:
            - DB_SERVER_HOST=zabbix_db
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_USER_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - ./volumes/zabbix/usr:/usr/lib/zabbix
            - ./volumes/zabbix/var:/var/lib/zabbix
        depends_on:
            - zabbix_db

    zabbix_db:
        container_name: zabbix_db
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_USER_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - ./volumes/mysql:/var/lib/mysql

    zabbix_nginx:
        container_name: zabbix_nginx
        image: zabbix/zabbix-web-nginx-mysql:alpine-4.4.3
        restart: always
        environment:
            - ZBX_SERVER_HOST=zabbix_server
            - DB_SERVER_HOST=zabbix_db
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_USER_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - PHP_TZ=${TIME_ZONE}
        ports:
            - ${HTTP_PORT}:80
        volumes:
            - ./volumes/mysql:/var/lib/mysql

    elastiflow-elasticsearch-oss:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.0
        container_name: elastiflow-elasticsearch-oss
        restart: always
#        ulimits:
#            memlock:
#            soft: -1
#            hard: -1
        volumes:
            - ./volumes/elastiflow_es:/usr/share/elasticsearch/data
        environment:
            ES_JAVA_OPTS: '-Xms2g -Xmx2g'
            cluster.name: elastiflow
            bootstrap.memory_lock: 'true'
            network.host: 0.0.0.0
            http.port: 9200
            discovery.type: 'single-node'
            indices.query.bool.max_clause_count: 8192
            search.max_buckets: 100000
            action.destructive_requires_name: 'true'

    elastiflow-kibana-oss:
        image: docker.elastic.co/kibana/kibana-oss:7.3.0
        container_name: elastiflow-kibana-oss
        restart: always
        environment:
            SERVER_HOST: 0.0.0.0
            SERVER_PORT: 5601
            SERVER_MAXPAYLOADBYTES: 4194304
            ELASTICSEARCH_HOSTS: "http://elastiflow-elasticsearch-oss:9200"
            KIBANA_DEFAULTAPPID: "dashboard/653cf1e0-2fd2-11e7-99ed-49759aed30f5"
            LOGGING_DEST: stdout
            LOGGING_QUIET: 'false'
        ports:
            - 5601:5601
        depends_on:
            - elastiflow-elasticsearch-oss    

    elastiflow-logstash-oss:
        image: robcowart/elastiflow-logstash-oss:3.5.1
        container_name: elastiflow-logstash-oss
        restart: always
        environment:
            LS_JAVA_OPTS: '-Xms4g -Xmx4g'
            ELASTIFLOW_DEFAULT_APPID_SRCTYPE: "__UNKNOWN"
            ELASTIFLOW_RESOLVE_IP2HOST: "false"
            ELASTIFLOW_NAMESERVER: "127.0.0.1"
            ELASTIFLOW_NETFLOW_IPV4_PORT: 2055
            ELASTIFLOW_SFLOW_IPV4_PORT: 6343
            ELASTIFLOW_IPFIX_TCP_IPV4_PORT: 4739
            ELASTIFLOW_ES_HOST: "elastiflow-elasticsearch-oss:9200"
        depends_on:
            - elastiflow-elasticsearch-oss
        ports:
            - 2055:2055/udp

    influxdb:
        image: influxdb:1.7.9-alpine
        container_name: influxdb
        volumes:
            - ./volumes/influxdb:/var/lib/influxdb
        ports:
            - 8083:8083
            - 8086:8086
        restart: always

    grafana:
        image: grafana/grafana:6.5.1
        container_name: grafana
        restart: always
        volumes:
            - ./volumes/grafana:/var/lib/grafana
        user: "104"
#        environment:
#            - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
#            - GF_SERVER_DOMAIN=ictsc.local
#            - GF_SERVER_ROOT_URL=https://ictsc.local/grafana
#            - GF_AUTH.BASIC_ENABLED=false
        ports:
            - 3000:3000

    unbound:
        container_name: unbound
        image: mvance/unbound:1.9.5
        restart: always
        volumes:
            - ./unbound:/opt/unbound/etc/unbound
        ports:
            - 53:53/udp
            - 53:53/tcp

    nginx:
        container_name: nginx
        image: nginx:1.17.6-alpine
        restart: always
#       volumes:
#           - ./volumes/influxdb:/var/lib/influxdb
        ports:
            - 80:80
            - 443:443

    logstash_syslog:
        image: docker.elastic.co/logstash/logstash-oss:7.3.0
        container_name: logstash_syslog
        volumes:
            - ./logstash-syslog/:/usr/share/logstash/pipeline
        ports:
            - 514:5140/udp
            - 514:5140/tcp
        depends_on:
            - elastiflow-elasticsearch-oss

